# 开发环境
# spring相关配置
spring:
    # 数据源配置
    datasource:
        # 内容发布数据库
        default:
            url: jdbc:mysql://192.168.1.254:3306/sinowcm?zeroDateTimeBehavior=convertToNull&relaxAutoCommit=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver

# 服务器
server:
    #端口
    port: 9301
